ABORT_CONTROLLER = 'abort_controller'
LCD_SCREEN_CONTROLLER = 'lcd_screen_controller'
MOTION_CONTROLLER = 'motion_controller'
REMOTE_CONTROLLER_CONTROLLER = 'remote_controller_controller'

LCD_SCREEN_SHOW_ABORT_CONTROLLER_OK_ON = ABORT_CONTROLLER + ' OK ON'
LCD_SCREEN_SHOW_ABORT_CONTROLLER_OK_OFF = ABORT_CONTROLLER + ' OK OFF'
LCD_SCREEN_SHOW_ABORT_CONTROLLER_NOK = ABORT_CONTROLLER + ' NOK'

LCD_SCREEN_SHOW_REMOTE_CONTROLLER_CONTROLLER_OK = REMOTE_CONTROLLER_CONTROLLER + ' OK'
LCD_SCREEN_SHOW_REMOTE_CONTROLLER_CONTROLLER_SEARCHING = REMOTE_CONTROLLER_CONTROLLER + ' SEARCHING'
LCD_SCREEN_SHOW_REMOTE_CONTROLLER_CONTROLLER_NOK = REMOTE_CONTROLLER_CONTROLLER + ' NOK'

LCD_SCREEN_CONTROLLER_ACTION_ON = LCD_SCREEN_CONTROLLER + ' ON'
LCD_SCREEN_CONTROLLER_ACTION_OFF = LCD_SCREEN_CONTROLLER + ' OFF'

ABORT_CONTROLLER_ACTION_ABORT = 'abort'
ABORT_CONTROLLER_ACTION_ACTIVATE = 'activate'